import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tailwind next js app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Home /> */}
      <h1 className=" w-100 bg-black text-white min-h-screen">
        <div className=" flex  bg-red-900">
          <div className=" hidden lg:block w-[var(--left-sidebar-width)] bg-slate-500 max-h-screen min-h-screen">
            <div className=" w-100 grid place-items-center h1">
              <h1>Netflix</h1>
            </div>
          </div>
          <div className="  bg-orange-500 flex-1  max-h-screen min-h-screen">
            a
          </div>
        </div>
      </h1>
      {/* <div>a</div> */}
    </>
  );
}
